### ISSUE TITLE
[힙] 9월 3주차

### ISSUE THREAD

**Issue by LudaStar** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#111]
#### [공통문제]
- ```힙``` 프로그래머스, 디스크 컨트롤러
- ```힙``` 프로그래머스, 이중우선순위큐
- ```문자열``` 백준, 3107 IPv6

#### 오늘 푼 문제
- ```힙``` 프로그래머스, 더 맵게

#### 개인 문제
- 아무거나 2개

### 추석 연휴로 한 주 쉬고 9/29일에 다시 만나용🎈
맛있는거 많이 먹어영!!🥘🍝🍗

**Comment by johyeoncheol** [comment]
+ 공통 문제
백준 3107 IPv6  🔥

**Comment by LudaStar** [comment]
> 추가로
> 
> * 공통 문제
>   백준 3107 IPv6  🔥

앗 이걸 빼먹었네여 감사함당 :)
역시 성애님이 필요행..ㅠ

**Comment by seongaeee** [comment]
ㅋㅋㅋㅋㅋㅋ 저도 제가 잘알았는지 확인하는 용도로 쓴답니다 😉

**Comment by Mulgyeol** [comment]
공통문제와 개인문제를 풀고 push!? 막히는 부분은 이슈에서 같이 이야기 하나요!?

**Comment by seongaeee** [comment]
> 공통문제와 개인문제를 풀고 push!? 막히는 부분은 이슈에서 같이 이야기 하나요!?

공통문제만 이슈에 쓰고, 댓글로 피드백~~~

**Comment by LudaStar** [comment]
> 공통문제와 개인문제를 풀고 push!? 막히는 부분은 이슈에서 같이 이야기 하나요!?

꺅 물결늼 참여하시는건가여?! 기대하고 있겠습니당ㅎㅎㅎ
