### ISSUE TITLE
[정렬] 9월 4주차

### ISSUE THREAD

**Issue by seongaeee** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#127]
#### [공통문제]
- `정렬` 프로그래머스, 가장 큰 수 
- `완전탐색` 프로그래머스, 카펫
- `시뮬레이션` 백준, 2824 최대공약수

#### 오늘 푼 문제
- `정렬` 프로그래머스, H-Index

#### 개인 문제
- 자율!

#### 공지사항

- 다음주(10.6)는 싸피 플젝 준비로 한 주 쉽니다 ! (성은님의 강력한 의견) 🔥

**Comment by cse96** [comment]
👍

**Comment by johyeoncheol** [comment]
윗분이 가짜입니다

**Comment by seongaeee** [comment]
임포스터!

**Comment by LudaStar** [comment]
아니 그래서 쉰다는건 팩트인건가여 여러분..?ㅋㅋㅋㅋㅋㅋㅋ

**Comment by seongaeee** [comment]
> 아니 그래서 쉰다는건 팩트인건가여 여러분..?ㅋㅋㅋㅋㅋㅋㅋ

쉽니당!!

**Comment by Jihogrammer** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ이게 모야
