### ISSUE TITLE
[String] 7월 4주 차

### ISSUE THREAD

**Issue by Jihogrammer** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#82]
###### 성지현, 최성은, 임성애, 김지호, 그리고 새 멤버 [조현철](https://github.com/johyeoncheol)

- 1주일에 `공통 1문제` + `자율 3문제`
- 이번 주는 `자율 3문제`도 `문자열`로 선택하나, 차주부터는 주제까지 자율로 진행한다.
- `공통 1문제`는 난도를 올려 원래 계획(DFS → BFS → ...) 주제 순서대로 고정하고 문제는 만나서 선정한다.
- 추가하고 싶은 알고리즘 종류는 수시로 공유한다.
- 1주일 할당량을 채우지 못할 경우 **1만 원의 벌금**이 있다.

##### 추가하고 싶은 주제 있으면 댓글로 남겨주세요!

> README 파일은 제가 손보겠습니다...
> `@` 입력하면 멤버 목록 뜨니까, 문제 선정되면 지금처럼 이슈 열어서 멘션이나 카톡 부탁드립니다(**MM 사절**).

**Comment by Jihogrammer** [comment]
#### 추가하고 싶은 주제 : KMP
@LudaStar @cse96 @seongaeee @johyeoncheol 

> @Mulgyeol 님도 끼셔도 됩니다.

**Comment by Jihogrammer** [comment]
### 추가하고 싶은 주제

- 덱 deque
- 재귀 recursive
- (쉬운) 그리디 greedy
- 정규식 regular expression

**Comment by seongaeee** [comment]
##### 2021.07.28

- 이번주 : `Deque` 1문제 + `자율` 3문제
- 오늘 푼 문제 : 백준, 5052 전화번호 목록
