### ISSUE TITLE
[Deque] 7월 5주차

### ISSUE THREAD

**Issue by LudaStar** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#86]
2021.07.28
이번주 : Deque 1문제 + 자율 3문제
오늘 푼 문제 : 백준 5052 전화번호 목록
공통문제 : 3190 뱀 (Deque)

**Comment by Jihogrammer** [comment]
저는 당분간 파이썬으로 전향하겠습니다,,,!
