### ISSUE TITLE
[Recursive] 8월 1주차

### ISSUE THREAD

**Issue by seongaeee** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#87]
##### 2021.08.04

- 이번주 : `Recursive` 1문제 + `자율` 3문제
- 이번주 공통 문제: 백준, 4902 삼각형의 값
- 오늘 푼 문제 : 백준, 2630 색종이 만들기

**Comment by Jihogrammer** [comment]
### 8월 11일부터 19:30에서 `오후 8시 30분`으로 시간 변경! (감사합니다😊)
