### ISSUE TITLE
[해시] 9월 1주차

### ISSUE THREAD

**Issue by seongaeee** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#90]
#### [공통 문제]
- `구현` 백준 15686 치킨 배달
- `해시` 프로그래머스 베스트앨범

#### 오늘 푼 문제
- `해시` 프로그래머스 완주하지 못한 선수

#### 공지

- 공통 문제 코드는 이슈에 올리기
- 수요일 낮 12시까지 다른 스터디원의 코드 리뷰 ✏️ 달기!

**Comment by cse96** [comment]
확인!
