### ISSUE TITLE
[지호][해시][9월1주][PGMS] 완주하지 못한 선수

### ISSUE THREAD

**Issue by Jihogrammer** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#91]
```py
def solution(participant, completion):
    hash_table = dict()
    hashValue = 0
    for p in participant:
        hash_table[hash(p)] = p
        hashValue += hash(p)
    for c in completion:
        hashValue -= hash(c)
    return hash_table[hashValue]
```

#### 해설
- 해시값을 추출해주는 메소드(`hash()`)를 활용
- 참여자의 해시값을 모두 더하고, 완주자의 해시값을 모두 빼주면 미완주자의 해시값만 남음
- 해당 해시값으로 이미 딕셔너리에 저장해둔 참여자 목록에서 조회하여 리턴
#### 결과
![image](https://user-images.githubusercontent.com/75299843/131675018-6c48a55d-1b78-428d-938e-fddcde95174d.png)

**Comment by LudaStar** [comment]
자바밖에 모르는 바보는 지호님의 자바 코드를 못 봐서 아쉬울 뿐..ㅠ

**Comment by johyeoncheol** [comment]
오 잘봤습니다
파이썬을 이렇게 배우네요 ㅎㅎ

**Comment by cse96** [comment]
잘봤습니다!
