### ISSUE TITLE
[성애][해시][9월1주][PGMS] 완주하지 못한 선수

### ISSUE THREAD

**Issue by seongaeee** [SSAFY-5th-GwanJu-4C-Algorithms/Algorithm_basic#92]
### 풀이 방법

해시 알고리즘을 억지로 껴넣고 풀려다보니 약간 더럽게 풀었습니다.. 💧 

**1) Map<String, Integer> 선언**
`String`은 이름, `Integer`은 해당 이름을 가진 선수의 수.

```java
Map<String, Integer> m = new HashMap();
```

<br>

**2) 마라톤에 참가한 선수 처리**
participant 배열을 순회하면서, Map에 값을 넣음. 
이때, 이미 이름이 있다면 선수의 수를 하나 늘려서 수정.

```java
for(int i = 0; i < participant.length; i++){
    if(m.containsKey(participant[i])) {
        int cnt = m.get(participant[i])+1;
        m.put(participant[i], cnt);
    } else {
        m.put(participant[i], 1);    
    }
}
```

<br>

**3) 마라톤에 완주한 선수 처리**
completion 배열을 순회하면서, 해당 이름을 가진 선수의 수를 하나 줄여서 수정.

```java
for(int i = 0; i < completion.length; i++){
    int cnt = m.get(completion[i])-1;
    m.put(completion[i], cnt);
}
```

<br>

**4) 마라톤에 완주하지 못한 선수 출력**
Map을 순회하면서, Integer가 0이 아니면 완주하지 못한 선수임.

```java
String answer="";
for(String s : m.keySet()){
    
    if(m.get(s) != 0){
        answer = s;
        break;
    }
}
return answer;
```

<br>

### 채점 결과

<img src="https://user-images.githubusercontent.com/62600984/131852075-c1c0512f-1186-4f48-bd43-661a4dcecbd5.png" width =300>

**Comment by Jihogrammer** [comment]
와 Java 문법 다 까먹겠다.

**Comment by LudaStar** [comment]
근데 해시 써서 풀려면 어쩔 수 없이 이렇게 되는거 같던데용ㅠ 💁🏻‍♀️

**Comment by johyeoncheol** [comment]
잘봤습니다 :)

**Comment by cse96** [comment]
깔끔하게 푸신거 같은데..? 잘봤습니다!
